# 标记t*标签，作为内部测试用
name: Stage
on:
  push:
    branches:
      - dev
    # tags:
    #   - t*

jobs:
  # release:
  #   name: Release on GitHub
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v1

  #   # - name: Info
  #   #   run: echo docker.pkg.github.com/${{ github.repository }}:${IMAGE_TAG}

  #   - name: Build docker & push
  #     uses: mr-smithers-excellent/docker-build-push@v2
  #     with:
  #       image: ${{ github.repository }}
  #       # tag: latest
  #       registry: registry.limei.net.cn
  #       dockerfile: Dockerfile
  #       username: ${{ secrets.REGISTRY_USERNAME }}
  #       password: ${{ secrets.REGISTRY_PASSWORD }}
  deploy:
    name: Deploy to sun
    runs-on: ubuntu-latest
    # needs: [docker]
    steps:
    # https://github.com/actions/checkout
    - name: Checkout deploy script
      uses: actions/checkout@v2
      with:
        repository: james70s/deploy-sun
        fetch-depth: 0
        token: ${{ secrets.GITHUB_PAT }} # `GitHub_PAT` is a secret that contains your PAT
        path: sun

    # - name: SSH bofore
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SUN_HOST }}
    #     key: ${{ secrets.SUN_DEPLOY_KEY }}
    #     username: ${{ secrets.SUN_HOST_USERNAME }}
    #     # password: ${{ secrets.SUN_HOST_PASSWORD }}
    #     port: ${{ secrets.SUN_HOST_PORT }}
    #     script: |
    #       rm -rf sunn
    #       ls -al

    # - name: copy file via ssh password
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.SUN_HOST }}
    #     # key: ${{ secrets.SUN_DEPLOY_KEY }}
    #     username: ${{ secrets.SUN_HOST_USERNAME }}
    #     password: ${{ secrets.SUN_HOST_PASSWORD }}
    #     port: ${{ secrets.SUN_HOST_PORT }}
    #     source: "sun/readme.md"
    #     target: "sunn"

    # - name: SSH after
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SUN_HOST }}
    #     key: ${{ secrets.SUN_DEPLOY_KEY }}
    #     username: ${{ secrets.SUN_HOST_USERNAME }}
    #     # password: ${{ secrets.SUN_HOST_PASSWORD }}
    #     port: ${{ secrets.SUN_HOST_PORT }}
    #     script: |
    #       ls -al

    # # https://github.com/marketplace/actions/ssh-and-scp-setup
    - name: SSH
      uses: alinz/ssh-scp-action@master
      env:
        HELLO: cool
        MESSAGE: hello world
      with:
        key: ${{ secrets.SUN_DEPLOY_KEY }}
        host: ${{ secrets.SUN_HOST }}
        user:  ${{ secrets.SUN_HOST_USERNAME }}
        port: ${{ secrets.SUN_HOST_PORT }}
        # runs this on remove server
        ssh_before: |
          rm -rf sun
          echo $HELLO
          echo $MESSAGE
    
        # then uploads these 2 files
        scp: |
          sun ${{ secrets.SUN_HOST_USERNAME }}@${{ secrets.SUN_HOST }}:~/sun -r
    
        # then run these commands
        ssh_after: |
          echo $HELLO
          echo $MESSAGE


  # deploy:
  #   name: Deploy to Host
  #   runs-on: ubuntu-latest
  #   # needs: [docker]
  #   steps:
  #   - name: Login to host and deploy
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.SUN_HOST }}
  #       key: ${{ secrets.SUN_DEPLOY_KEY }}
  #       username: ${{ secrets.SUN_HOST_USERNAME }}
  #       # password: ${{ secrets.SUN_HOST_PASSWORD }}
  #       port: ${{ secrets.SUN_HOST_PORT }}
  #       # script: whoami
  #       script: |
  #         cd sun
  #         git pull
  #         ls -al